spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://identity-mysql:3306/identity_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:}
  public-key-path: ${JWT_PUBLIC_KEY_PATH:}
  expiration-seconds: 1800
  service-token-expiration-seconds: ${JWT_SERVICE_TOKEN_EXPIRATION_SECONDS:300}
